### ISSUE TITLE
Render user.displayName as minecraft-nickname

### ISSUE THREAD

**Issue by bushidocodes** [TranscendVR/transcend#44]
So like if you login as yoo-nah@transcend.vr, yoo-nah's avatar displays 'TheChair' over her head.

**Comment by bethqiang** [comment]
Also don't think this is terribly difficult. I'm not sure how @Jmikeydarby is displaying their color hex above their head right now, but I can imagine it being relatively little work to change that to literally just be `user.displayName`.
