### ISSUE TITLE
Add Minecraft skin as attribute on User object and allow user to select

### ISSUE THREAD

**Issue by bushidocodes** [TranscendVR/transcend#45]
These functions would have to render the skinUrl from `user.skin`:
/browser/utils/putUserOnDOM
/browser/utils/putUserBodyOnDOM

We could modify user.color be user.skin and user 3d-jesus as a default.

We would then need a way to let users pick their skin. How about one of the rooms is a dressing room that displays all of the skins and if a user clicks on one, the `user.skin` is set to that skin?

**Comment by bushidocodes** [comment]
If we want the user to be able to select the skin at registration, we might want to figure out a way to pass this into the User constructor itself.

**Comment by bethqiang** [comment]
So if we want the user to be able to select the skin at registration....................
....................this would not be very difficult.

(Literally, we have all the skins loaded and incorporated, we'd just have to give the user the option and set it with all their other information.)

(Like, this is low-hanging fruit.)

(I say let's do it.)

**Comment by bethqiang** [comment]
Closed by #88
