### ISSUE TITLE
Route Hacking iz Real

### ISSUE THREAD

**Issue by leafoflegend** [TranscendVR/transcend#56]
hit this: https://transcend.herokuapp.com/vr/lobby

It will just send ya right into the app. Need some backend authentication on this route otherwise - people may bookmark that link - hit it unlogged in or post cookie expiration - and it will cause your app all sorts of nightmares to see `user = null`.

**Comment by bethqiang** [comment]
Same as #30. Expect to be fixed with merge of @spmcbride1201's most recent PR (#55). Closing this & leaving 30 open until merge.
