### ISSUE TITLE
Move App container to App component to be consistent with Beth's Login component

### ISSUE THREAD

**Issue by bushidocodes** [TranscendVR/transcend#59]
Our standard would be to place React-Redux containers at the bottom of the files that define the Component.

**Comment by bushidocodes** [comment]
This is fixed in the `branch-container-refactor` branch, but since it's branched off my PR, I'll standby until that's merged / fixed and then get the PR up.

**Comment by bethqiang** [comment]
If that's the only change you made in that branch, why not just include it in the current PR? Seems like it'd be slightly more efficient all around.
